
# SEO settings
title: "0"
title2: "abfuhr" # default: ""
description: "Mit ganz viel Liebe und wirklich unfassbar wenig Skill."
url: http://arduqq.github.io/ # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/arduqq/0abfuhr
disqus_shortname: "arduqq"
twitter_username: "arduuq"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Artur Solomonik"
  job      : "Medieninformatik-Student"
  bio      : "Ich mag hübsche Förmchen und verteile Boxringe an Blinde."
  thumb    : /images/author.jpg
  email    : artur.solomonik@uni-weimar.de
  url      : http://arduqq.github.io
  github   : http://github.com/arduqq
  twitter  : http://twitter.com/arduuq

# social settings
og_locale: "de_DE"
twitter_card: "summary_large_image"
twitter_site: "@Arduuq"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
